const userId = 44;
const exampleChatRooms = [
  {
    roomId: 1,
    roomName: "사과왕, 채소마니아와의 대화",
    roomType: "그룹",
    participants: [
      {
        userId: 1,
        nickname: "사과왕",
        profileImageUrl: "https://iili.io/23GIx5b.png",
      },
      {
        userId: 2,
        nickname: "채소마니아",
        profileImageUrl: "https://iili.io/23GIzej.png",
      },
      {
        userId: 3,
        nickname: "과일킬러",
        profileImageUrl: "https://iili.io/23hQgd7.png",
      },
      {
        userId: userId,
        nickname: "과일러버",
        profileImageUrl: "https://iili.io/23w902j.png",
      },
      {
        userId: 4,
        nickname: "두리안킬러",
        profileImageUrl: "https://iili.io/23GIuzQ.png",
      },
      {
        userId: 5,
        nickname: "딸기맛있엉",
        profileImageUrl: "https://iili.io/23GIuzQ.png",
      },
    ],
    lastMessage: "사과 10kg에 얼마로 가능하신가요?",
    lastMessageSender: "사과왕",
    lastMessageTime: "2024-10-19T10:30:00Z",
    unreadMessageCount: 99,
    createdAt: "2024-10-19T10:30:00Z",
  },
  {
    roomId: 2,
    roomName: "유기농러버",
    roomType: "개인",
    participants: [
      {
        userId: 3,
        nickname: "유기농러버",
        profileImageUrl: "https://iili.io/23GIuzQ.png",
      },
      {
        userId: userId,
        nickname: "감자매니아",
        profileImageUrl: "https://iili.io/23GIzej.png",
      },
    ],
    lastMessage: "유기농 당근 3kg에 가격 조정 가능할까요?",
    lastMessageSender: "유기농러버",
    lastMessageTime: "2024-10-17T07:15:00Z",
    unreadMessageCount: 10,
    createdAt: "2024-10-17T07:15:00Z",
  },
  {
    roomId: 3,
    roomName: "과일 사랑하는 사람들",
    roomType: "그룹",
    participants: [
      { userId: 6, nickname: "과일사랑", profileImageUrl: "https://iili.io/23GIx5b.png" },
      { userId: userId, nickname: "수박매니아", profileImageUrl: "https://iili.io/23GIzej.png" },
      { userId: 8, nickname: "포도왕", profileImageUrl: "https://iili.io/23hQgd7.png" },
      { userId: 5, nickname: "딸기맛있엉", profileImageUrl: "https://iili.io/23GIuzQ.png" },
    ],
    lastMessage: "다음 주 수박 모임 어때요?",
    lastMessageSender: "수박매니아",
    lastMessageTime: "2023-10-18T12:00:00Z",
    unreadMessageCount: 0,
    createdAt: "2023-10-16T12:00:00Z",
  },
  {
    roomId: 4,
    roomName: "과일과 채소의 조화",
    roomType: "그룹",
    participants: [
      { userId: userId, nickname: "채소전문가", profileImageUrl: "https://iili.io/23GIzej.png" },
      { userId: 13, nickname: "헬시푸드", profileImageUrl: "https://iili.io/23hQgd7.png" },
    ],
    lastMessage: "샐러드 레시피 공유해요!",
    lastMessageSender: "헬시푸드",
    lastMessageTime: "2024-10-22T15:45:00Z",
    unreadMessageCount: 3,
    createdAt: "2024-10-14T08:30:00Z",
  },
  {
    roomId: 5,
    roomName: "베지테리언 모임",
    roomType: "그룹",
    participants: [{ userId: userId, nickname: "비건", profileImageUrl: "https://iili.io/23GIzej.png" }],
    lastMessage: "비건 레시피 공유해요!",
    lastMessageSender: "베지테리언",
    lastMessageTime: "2024-10-20T18:00:00Z",
    unreadMessageCount: 2,
    createdAt: "2024-10-12T11:00:00Z",
  },
  {
    roomId: 6,
    roomName: "채소 직거래",
    roomType: "그룹",
    participants: [
      { userId: 17, nickname: "직거래왕", profileImageUrl: "https://iili.io/23GIx5b.png" },
      { userId: userId, nickname: "신선한채소", profileImageUrl: "https://iili.io/23GIzej.png" },
      { userId: 19, nickname: "농부", profileImageUrl: "https://iili.io/23hQgd7.png" },
    ],
    lastMessage: "이번 주 채소 가격 알려주세요.",
    lastMessageSender: "직거래왕",
    lastMessageTime: "2024-10-21T12:30:00Z",
    unreadMessageCount: 1,
    createdAt: "2024-10-11T16:30:00Z",
  },
];
export default exampleChatRooms;
